#!/usr/bin/env bash
# tractseg_fixel_connectivity_and_smoothing.sh
#
# Compute fixel-fixel connectivity matrices and smooth FBA metric maps using tractograms
# generated by TractSeg (TOM-based Tracking).
#
# Reference:
#   https://github.com/MIC-DKFZ/TractSeg
#
# Prerequisites:
#   - TractSeg Tracking outputs (*.tck)
#   - MRtrix3 on PATH (tck2fixel, fixelcrop, fixelconnectivity, fixelfilter)
#   - A template-space fixel mask directory (from MRtrix FBA pipeline)
#
# Created by Idy Chou on 25 Mar 2025

# ----------------------------- user parameters ------------------------------
topDir="/path/to/processed_data"

# Template / FBA resources
fbaDir="${topDir}/template/fba"                 # contains fixel_mask/
fixelMaskDir="${fbaDir}/fixel_mask"             # fixel mask directory used for cropping & connectivity

# Input TractSeg tractograms
inDir="/absolute/path/to/TractSeg/outputs/TOM_trackings"   # directory containing *.tck

# Metric fixel directories (one directory per metric, containing subject metric files + index/directions)
# Expected by this script:
#   ${fbaDir}/${metric}_harmonized/
#     index.mif
#     directions.mif
#     sub-*.mif   (subject data files already in template fixel space)
outDir="${topDir}/group_data/TractSeg_fwhm_10"

# Smoothing kernel for fixelfilter
fwhm="10"

# Which metrics to process
metrics="fd log_fc fdc"
# ---------------------------------------------------------------------------

sep="--------------------------------------------------------"

# Create common output directories
mkdir -p "${outDir}"
mkdir -p "${outDir}/matrix"
mkdir -p "${outDir}/tract_fixels/tractseg_tdi"
mkdir -p "${outDir}/tract_fixels/group_fixels"

# Loop over metrics
for metric in ${metrics}; do
  metricDir="${fbaDir}/${metric}_harmonized"

  if [ ! -d "${metricDir}" ]; then
    echo "ERROR: Metric directory not found: ${metricDir}"
    exit 1
  fi

  mkdir -p "${outDir}/${metric}"
  mkdir -p "${outDir}/${metric}_smooth"

  # Copy metric maps into a unified directory (required for cropping per tract)
  printf "\n%s\nCopying %s files...\n%s\n" "${sep}" "${metric}" "${sep}"

  # Copy subject metric files (match your naming conventions here)
  for file in "${metricDir}"/sub-*.mif; do
    [ -f "${file}" ] || continue
    cp "${file}" "${outDir}/${metric}/"
  done

  # Copy fixel metadata
  cp "${metricDir}/directions.mif" "${outDir}/${metric}/directions.mif"
  cp "${metricDir}/index.mif" "${outDir}/${metric}/index.mif"

  # Iterate over tractograms
  cd "${inDir}" || exit 1

  for tck in *.tck; do
    [ -f "${tck}" ] || continue
    tract="$(basename "${tck}" .tck)"

    printf "\n%s\nTract: %s\n%s\n" "${sep}" "${tract}" "${sep}"

    # 1) Convert tractogram to a fixel TDI map in template fixel space
    tdi_file="${outDir}/tract_fixels/tractseg_tdi/${tract}_tdi.mif"
    if [ ! -f "${tdi_file}" ]; then
      echo "Converting tractogram to TDI map..."
      tck2fixel "${inDir}/${tract}.tck" "${fixelMaskDir}" "${outDir}/tract_fixels/tractseg_tdi" "${tract}_tdi.mif"
    fi

    # 2) Crop the whole-brain template fixel mask to tract-specific fixels
    tract_fixel_dir="${outDir}/tract_fixels/group_fixels/${tract}"
    if [ ! -d "${tract_fixel_dir}" ]; then
      echo "Extracting tract from fixel mask..."
      fixelcrop "${fixelMaskDir}" "${tdi_file}" "${tract_fixel_dir}"
    fi

    # 3) Build fixel-fixel connectivity matrix for this tract
    matrix_dir="${outDir}/matrix/${tract}"
    if [ ! -d "${matrix_dir}" ]; then
      echo "Calculating fixel-fixel connectivity..."
      fixelconnectivity "${tract_fixel_dir}" "${inDir}/${tract}.tck" "${matrix_dir}"
    fi

    # 4) Crop the metric fixel data to this tract (using the same TDI map)
    tract_metric_dir="${outDir}/${metric}/${tract}"
    if [ ! -d "${tract_metric_dir}" ]; then
      echo "Cropping ${metric} data using TDI map..."
      fixelcrop "${outDir}/${metric}" "${tdi_file}" "${tract_metric_dir}"
    fi

    # 5) Smooth cropped metric data using tract-specific connectivity matrix
    smooth_dir="${outDir}/${metric}_smooth/${tract}"
    if [ ! -d "${smooth_dir}" ]; then
      echo "Smoothing ${metric} data using connectivity matrix (fwhm=${fwhm})..."
      fixelfilter "${tract_metric_dir}" smooth "${smooth_dir}" -matrix "${matrix_dir}" -fwhm "${fwhm}"
    fi
  done

  # Optional cleanup: remove uncropped per-metric directory (big)
  rm -rf "${outDir:?}/${metric}"
done

printf "\n%s\nDone.\n" "${sep}"
